[plot]
# A görbén megjelenő szövegek mérete.
# Alapértelmezett érték: 10
font_size = 10

# A görbe vonalvastagsága.
# Alapértelmezett érték: 3
line_width = 3

# A felső X tengelyen lévő eseményjelölők mérete.
# Alapértelmezett érték: 13
event_marker_size = 13

# A földrengés kipattanást jelölő pötty színe és mérete.
# A szín megadható szöveges és hexadecimális formátumban is.
# pl. "yellow" vagy "#FFFF00"
# Alapértelmezett értékek: "cyan" és 8
occurrence_marker_color = "cyan"
occurrence_marker_size = 8

[path]
# A program futásához szükséges fájlok elérési útjai.
# Alapértelmezett értékek: "datumok.txt" és "tsf_viewer_ftp.json"
# (Ebben az esetben a projekt könyvtárban keressük a fájlokat)
datumok_txt = "datumok.txt"
ftp_json = "tsf_viewer_ftp.json"

[earthquake]
# A földrengések lekérdezésére szolgáló API hívás elérési címe.
# Fontos, hogy a link "/fdsnws/event/1/query"-re kell végződjön.
# Alapértelmezett érték: "https://geofon.gfz-potsdam.de/fdsnws/event/1/query"
api_url = "https://geofon.gfz-potsdam.de/fdsnws/event/1/query"

[compression]
# Az ennél nagyobb TSF fájlokat a program HDF5 formátumba tömöríti.
# Érdemes a teljes RAM méretének felét megadni, GB (gigabyte) formátumban.
# Ezeket a bináris állományokat sokkal gyorsabban olvassa be a program,
# ezért a gyakran megnyitott fájlokat érdemes tömöríteni. A legegyszerűbb
# módja ennek a file_size_limit = 0 értékre való állítása. Ilyenkor futtatás
# után a program automatikusan megkérdezi, hogy kívánjuk-e tömöríteni.
# Alapértelmezett érték: 4
file_size_limit = 4

# A legenerált és tömörített HDF5 (.h5) fájlok mentési helye.
# Windowson KÖTELEZŐ ilyenkor a dupla backslash ("\\") a mappák jelölésénél!
# Az elérési út végére nem kell backslash. pl. "C:\\Users\\Public"
#
# Ha csillagot ("*") adunk meg, az eredeti fájl helyére fogja végezni a tömörítést.
# Alapértelmezett érték: "*"
h5_save_path = "*"
